name: firebase_analytics_web
description: The web implementation of firebase_analytics
homepage: https://github.com/firebase/flutterfire/tree/main/packages/firebase_analytics/firebase_analytics_web
repository: https://github.com/firebase/flutterfire/tree/main/packages/firebase_analytics/firebase_analytics_web
version: 0.6.1+4
resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  firebase_analytics_platform_interface: ^4.2.10
  firebase_core: ^3.10.1
  firebase_core_web: ^3.5.1
  meta: ^1.18.0

dev_dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseAnalyticsWebRegistration
        fileName: firebase_analytics_web_registration.dart
