name: cloud_functions_web
description: The web implementation of cloud_functions
homepage: https://github.com/firebase/flutterfire/tree/main/packages/cloud_functions/cloud_functions_web
repository: https://github.com/firebase/flutterfire/tree/main/packages/cloud_functions/cloud_functions_web
version: 5.1.4
resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  cloud_functions_platform_interface: ^5.5.9
  firebase_core: ^3.10.1
  firebase_core_web: ^3.5.1
  meta: ^1.18.0

dev_dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseFunctionsWebRegistration
        fileName: cloud_functions_web_registration.dart
