name: cloud_firestore_web
description: The web implementation of cloud_firestore
homepage: https://github.com/firebase/flutterfire/tree/main/packages/cloud_firestore/cloud_firestore_web
repository: https://github.com/firebase/flutterfire/tree/main/packages/cloud_firestore/cloud_firestore_web
version: 5.2.0
resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  cloud_firestore_platform_interface: ^6.4.10
  firebase_core: ^3.10.1
  firebase_core_web: ^3.5.1
  meta: ^1.18.0

dev_dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseFirestoreWebRegistration
        fileName: cloud_firestore_web_registration.dart
